/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container": "#dbf1fe",
          "error-container": "#ffdad6",
          "inverse-on-surface": "#dff4ff",
          "surface-bright": "#f3faff",
          "on-error": "#ffffff",
          "secondary-container": "#a3ecf0",
          "on-tertiary-fixed": "#2a1800",
          "inverse-surface": "#1e333c",
          "on-surface-variant": "#40493d",
          "error": "#ba1a1a",
          "surface-container-highest": "#cfe6f2",
          "on-primary-fixed": "#002204",
          "surface-tint": "#1b6d24",
          "on-error-container": "#93000a",
          "secondary-fixed-dim": "#8ad3d7",
          "surface-variant": "#cfe6f2",
          "on-secondary": "#ffffff",
          "on-background": "#071e27",
          "secondary-fixed": "#a6eff3",
          "primary-fixed-dim": "#88d982",
          "on-surface": "#071e27",
          "on-tertiary-container": "#ffeede",
          "tertiary": "#774c00",
          "surface-container-low": "#e6f6ff",
          "inverse-primary": "#88d982",
          "surface-dim": "#c7dde9",
          "background": "#f3faff",
          "primary-container": "#2e7d32",
          "surface": "#f3faff",
          "on-secondary-container": "#1b6d71",
          "on-primary-container": "#cbffc2",
          "tertiary-container": "#986200",
          "primary-fixed": "#a3f69c",
          "on-tertiary": "#ffffff",
          "tertiary-fixed": "#ffddb5",
          "secondary": "#14696d",
          "on-secondary-fixed-variant": "#004f53",
          "on-tertiary-fixed-variant": "#643f00",
          "outline": "#707a6c",
          "surface-container-high": "#d5ecf8",
          "tertiary-fixed-dim": "#ffb957",
          "primary": "#0d631b",
          "surface-container-lowest": "#ffffff",
          "on-primary-fixed-variant": "#005312",
          "outline-variant": "#bfcaba",
          "on-primary": "#ffffff",
          "on-secondary-fixed": "#002021"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "maxWidth": {
          "md": "28rem",
          "2xl": "42rem",
          "3xl": "48rem",
          "container-max": "1280px"
      },
      "spacing": {
          "sm": "12px",
          "gutter": "24px",
          "xl": "80px",
          "lg": "48px",
          "container-max": "1280px",
          "xs": "4px",
          "md": "24px",
          "base": "8px"
      },
      "fontFamily": {
          "headline-md": ["Inter"],
          "body-md": ["Inter"],
          "body-lg": ["Inter"],
          "label-sm": ["Inter"],
          "label-lg": ["Inter"],
          "headline-lg": ["Inter"],
          "headline-xl-mobile": ["Inter"],
          "headline-xl": ["Inter"],
          "label-md": ["Inter"],
          "body-sm": ["Inter"],
          "headline-lg-mobile": ["Inter"]
      },
      "fontSize": {
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "label-sm": ["10px", { "lineHeight": "14px", "fontWeight": "500" }],
          "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
          "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
